django_templates_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("template_app/",include("template_app.urls")),
    path("admin/", admin.site.urls),
    
]

template_app/urls.py
from django.urls import path
from . import views
#app_name register 

app_name = "template_app"
urlpatterns = [
    path("",views.index,name="index"),
    path("weather/",views.weather_view,name="weatherview"),
    
]

template_app/models.py
from django.db import models

# Create your models here.

template_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
# Create your views here.

def index(request):
    return render(request,"template_app/first.html")



def weather_view(request):
    weather_dictionary = {
        "Istanbul" : "30",
        "Amsterdam" : "20",
        "Elazığ" : "25",
        "Paris" : [5,14,22,21],
        "rome" : {"morning" : 22, "night": 10},
        "user_premium" : True,
        "test" : "Test test TesT TEST"
    }
    return render(request,"template_app/weather.html",context=weather_dictionary)

template_app/templates/template_app/first.html
{% extends 'base.html' %}
{% load static %}

{%block content%}
<p>test test test</p>
<p>evet bu araya firstte yazdığın şey basede belirttiğin aynı araya geliyor</p>
<br><br>
<img style="max-width: 100px;max-height: 100px;" src="{% static 'template_app/ben.jpg' %}" alt="ben">
{%endblock%}

template_app/templates/template_app/weather.html
{%extends 'base.html' %}

{%block content%}
<h1>Weather Report</h1>
<!-- jinja syntax -->
 <h2>Istanbul Weather {{Istanbul}}</h2>
 <br>
 <h2>Amsterdam Weather {{Amsterdam}}</h2>
 <br>
    <ul>
        {% for key,value  in rome.items %}
            <li>Rome Weather {{key}} {{value}}</li>
        {% endfor %}
    </ul>
 

<br>
    {% if user_premium%}
        <h2>evet</h2>
        <ul>
        {% for item in Paris %}
            {% if item > 5 %}
                <li>Paris Weather {{item}}</li>
            {% else %}
                <li>Paris Weather cold {{item}}</li>
            {% endif %}
            
        {% endfor %}
        </ul>
    {% endif %}
<br>

    <h2>{{test|upper}}</h2>

<br>

<h2><a href="{%url 'template_app:index'%}">Go To Index</a></h2>
{%endblock%}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>My Main Website</title>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
  
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
  
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
  
        .bd-mode-toggle {
          z-index: 1500;
        }
  
        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
        body{
            min-height: 75rem;
            padding-top: 4.5rem;
        }
      </style>
  
      
      <!-- Custom styles for this template -->
      <link href="navbar-fixed.css" rel="stylesheet">
    </head>
    <body>
            
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">Weather App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'template_app:index'%}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'template_app:weatherview'%}">Weather Report</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
                </ul>
                <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
            </div>
        </nav>
        
            {% block content %}

            {% endblock %}
        
        <h1 style="margin-top: 40px;">END OF BASE HTML </h1>
        
    </body>
</html>